package proof_test

// corpus is the expressions the proof evaluates over the library: each
// function called as a configuration calls it, what HCL answers with
// go-cty's functions (a part of it where the whole is long), what it answers
// with tenon's, and where the two differ, the reason. PROOF_RECORD=1 prints
// the answers each expression gives now, to write a new one from.
var corpus = []entry{
	{`abs(-2.5)`, `cty.NumberFloatVal(2.5)`, `cty.NumberFloatVal(2.5)`, ``},
	{`abs(unknown)`, `cty.UnknownVal(cty.Number).RefineNotNull()`, `cty.UnknownVal(cty.Number).Refine().NotNull().NumberLowerBound(cty.NumberIntVal(0), true).NewValue()`, `an unknown operand's range carries into the answer: a magnitude is at least 0 (UN-007), where cty says only not null`},
	{`assertnotnull("x")`, `cty.StringVal("x")`, `cty.StringVal("x")`, ``},
	{`assertnotnull(nothing)`, `error: Invalid value for "v" parameter: argument must not be null.`, `error: Call to function "assertnotnull" failed: operation.null_operand: argument 1 (value) of AssertNotNull is null, which AssertNotNull cannot use at .[0].`, `both fail; tenon's failure has a code, located at the argument (LN-083, ER-001)`},
	{`ceil(1.2)`, `cty.NumberIntVal(2)`, `cty.NumberIntVal(2)`, ``},
	{`floor(-1.2)`, `cty.NumberIntVal(-2)`, `cty.NumberIntVal(-2)`, ``},
	{`signum(-3)`, `cty.NumberIntVal(-1)`, `cty.NumberIntVal(-1)`, ``},
	{`int(-2.7)`, `cty.NumberIntVal(-2)`, `cty.NumberIntVal(-2)`, ``},
	{`log(8, 2)`, `cty.NumberIntVal(3)`, `cty.NumberIntVal(3)`, ``},
	{`log(10, 3)`, `cty.NumberFloatVal(2.095903274289385)`, `cty.MustParseNumberVal("2.09590327428938460429656752202140125060751800679793011692354533863417747757194062871676580230898")`, `a logarithm is correctly rounded to 96 significant digits (LN-060), where cty's goes through a float64`},
	{`pow(2, 10)`, `cty.NumberIntVal(1024)`, `cty.NumberIntVal(1024)`, ``},
	{`pow(2, 0.5)`, `cty.NumberFloatVal(1.4142135623730951)`, `cty.MustParseNumberVal("1.41421356237309504880168872420969807856967187537694807317667973799073247846210703885038753432764")`, `a power is correctly rounded to 96 significant digits (LN-061), where cty's goes through a float64`},
	{`min(3, 1.5, 2)`, `cty.NumberFloatVal(1.5)`, `cty.NumberFloatVal(1.5)`, ``},
	{`max(3, 1.5, 2)`, `cty.NumberIntVal(3)`, `cty.NumberIntVal(3)`, ``},
	{`parseint("ff", 16)`, `cty.NumberIntVal(255)`, `cty.NumberIntVal(255)`, ``},
	{`parseint("-1010", 2)`, `cty.NumberIntVal(-10)`, `cty.NumberIntVal(-10)`, ``},
	{`parseint("12", 1)`, `error: Invalid value for "base" parameter: base must be a whole number between 2 and 62 inclusive.`, `error: Call to function "parseint" failed: function.invalid_argument: the base of ParseInt must be a whole number from 2 to 62, not 1 at .[1].`, `both fail; tenon's failure has a code, located at the base (LN-050)`},
	{`tonumber("1e2")`, `cty.NumberIntVal(100)`, `cty.NumberIntVal(100)`, ``},
	{`tonumber("1p4")`, `cty.NumberIntVal(16)`, `error: Call to function "tonumber" failed: number.invalid_syntax: "1p4" is not a number at .[0].`, `a string is read as a number by tenon's grammar, which refuses 1p4 (NU-022, Appendix B row 8)`},
	{`tostring(1000000)`, `cty.StringVal("1000000")`, `cty.StringVal("1000000")`, ``},
	{`tostring(1e30)`, `cty.StringVal("1000000000000000000000000000000")`, `cty.StringVal("1e30")`, `a number converts to its canonical text (NU-020, Appendix B row 32)`},
	{`tostring(true)`, `cty.StringVal("true")`, `cty.StringVal("true")`, ``},
	{`coalesce(null, "", "a")`, `cty.StringVal("")`, `cty.StringVal("")`, ``},
	{`coalesce(null, 1, "2")`, `cty.StringVal("1")`, `cty.StringVal("1")`, ``},
	{`coalescelist([], ["a"])`, `cty.TupleVal([]cty.Value{cty.StringVal("a")})`, `cty.TupleVal([]cty.Value{cty.StringVal("a")})`, ``},
	{`compact(["a", "", "b"])`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, ``},
	{`concat(["a"], ["b", "c"])`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, ``},
	{`contains(["a", "b"], "b")`, `cty.True`, `cty.True`, ``},
	{`contains([[1]], [1])`, `cty.True`, `cty.True`, ``},
	{`distinct(["a", "b", "a"])`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, ``},
	{`element(["a", "b", "c"], 4)`, `cty.StringVal("b")`, `cty.StringVal("b")`, ``},
	{`element(["a", "b"], -1)`, `cty.StringVal("b")`, `cty.StringVal("b")`, ``},
	{`flatten([["a", "b"], [], ["c"]])`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, ``},
	{`hasindex(["a"], 1)`, `cty.False`, `cty.False`, ``},
	{`index(["a", "b"], 1)`, `cty.StringVal("b")`, `cty.StringVal("b")`, ``},
	{`index(["a", "b"], "b")`, `error: Call to function "index" failed: key for tuple must be number.`, `error: Call to function "index" failed: operation.wrong_type: Index takes a number as the key of a tuple, not string at .[1].`, `both fail; tenon's failure has a code, located at the key (LC-003, ER-001)`},
	{`keys({b = 1, a = 2})`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, `cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, ``},
	{`values({b = 1, a = 2})`, `cty.TupleVal([]cty.Value{cty.NumberIntVal(2), cty.NumberIntVal(1)})`, `cty.TupleVal([]cty.Value{cty.NumberIntVal(2), cty.NumberIntVal(1)})`, ``},
	{`length("e\u0301x")`, `error: Call to function "length" failed: collection must be a list, a map or a tuple.`, `cty.NumberIntVal(2)`, `tenon's Length takes a string, counting its grapheme clusters, and an object, counting its attributes (LC-001), where cty's takes collections alone`},
	{`length(["a", "b"])`, `cty.NumberIntVal(2)`, `cty.NumberIntVal(2)`, ``},
	{`length({a = 1})`, `error: Call to function "length" failed: collection must be a list, a map or a tuple.`, `cty.NumberIntVal(1)`, `tenon's Length takes a string, counting its grapheme clusters, and an object, counting its attributes (LC-001), where cty's takes collections alone`},
	{`lookup({a = "x"}, "b", "y")`, `cty.StringVal("y")`, `cty.StringVal("y")`, ``},
	{`merge({a = 1}, {b = 2}, {a = 3})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(3), "b":cty.NumberIntVal(2)})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(3), "b":cty.NumberIntVal(2)})`, ``},
	{`merge(null, {a = 1})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(1)})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(1)})`, ``},
	{`range(3)`, `cty.ListVal([]cty.Value{cty.NumberIntVal(0), cty.NumberIntVal(1), cty.NumberIntVal(2)})`, `cty.ListVal([]cty.Value{cty.NumberIntVal(0), cty.NumberIntVal(1), cty.NumberIntVal(2)})`, ``},
	{`range(0, 1, 0.1)`, `cty.ListVal([]cty.Value{cty.NumberIntVal(0), cty.MustParseNumberVal("0.1"), cty.MustParseNumberVal("0.2"), cty.MustParse`, `cty.ListVal([]cty.Value{cty.NumberIntVal(0), cty.MustParseNumberVal("0.1"), cty.MustParseNumberVal("0.2"), cty.MustParseNumberVal("0.3"), cty.MustParseNumberVal("0.4"), cty.NumberFloatVal(0.5), cty.MustParseNumberVal("0.6"), cty.MustParseNumberVal("0.7"), cty.MustParseNumberVal("0.8"), cty.MustParseNumberVal("0.9")})`, `every element is exact (LC-050), where cty's steps drift in 512 binary bits past 0.7 (Appendix B row 5)`},
	{`range(5000)`, `error: Call to function "range" failed: more than 1024 values were generated; either decrease the difference between start and end or use a smaller step.`, `error: Call to function "range" failed: function.too_large: Range: from 0 to 5000 by 1 is more than 1024 elements, the most it makes at .[0].`, `both fail at the bound; tenon's failure has a code, located at the argument (LC-052)`},
	{`reverse(["a", "b", "c"])`, `cty.TupleVal([]cty.Value{cty.StringVal("c"), cty.StringVal("b"), cty.StringVal("a")})`, `cty.TupleVal([]cty.Value{cty.StringVal("c"), cty.StringVal("b"), cty.StringVal("a")})`, ``},
	{`sethaselement(toset(["a"]), "a")`, `cty.True`, `cty.True`, ``},
	{`setintersection(["a", "b"], ["b", "c"])`, `cty.SetVal([]cty.Value{cty.StringVal("b")})`, `cty.SetVal([]cty.Value{cty.StringVal("b")})`, ``},
	{`setproduct(["a", "b"], [1, 2])`, `cty.ListVal([]cty.Value{cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.NumberIntVal(1)}), cty.TupleVal([]cty.Value{cty`, `cty.ListVal([]cty.Value{cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.NumberIntVal(1)}), cty.TupleVal([]cty.Value{cty.StringVal("a"), cty.NumberIntVal(2)}), cty.TupleVal([]cty.Value{cty.StringVal("b"), cty.NumberIntVal(1)}), cty.TupleVal([]cty.Value{cty.StringVal("b"), cty.NumberIntVal(2)})})`, ``},
	{`setsubtract(["a", "b"], ["b"])`, `cty.SetVal([]cty.Value{cty.StringVal("a")})`, `cty.SetVal([]cty.Value{cty.StringVal("a")})`, ``},
	{`setsymmetricdifference(["a", "b"], ["b", "c"])`, `cty.SetVal([]cty.Value{cty.StringVal("a"), cty.StringVal("c")})`, `cty.SetVal([]cty.Value{cty.StringVal("a"), cty.StringVal("c")})`, ``},
	{`setunion(["b"], ["a"])`, `cty.SetVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, `cty.SetVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")})`, ``},
	{`slice(["a", "b", "c"], 1, 3)`, `cty.TupleVal([]cty.Value{cty.StringVal("b"), cty.StringVal("c")})`, `cty.TupleVal([]cty.Value{cty.StringVal("b"), cty.StringVal("c")})`, ``},
	{`sort(["b", "a", "c"])`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal("c")})`, ``},
	{`zipmap(["a", "b"], [1, 2])`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(1), "b":cty.NumberIntVal(2)})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.NumberIntVal(1), "b":cty.NumberIntVal(2)})`, ``},
	{`chunklist(["a", "b", "c"], 2)`, `cty.ListVal([]cty.Value{cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")}), cty.ListVal([]cty.Value{cty.StringVal("c")})})`, `cty.ListVal([]cty.Value{cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b")}), cty.ListVal([]cty.Value{cty.StringVal("c")})})`, ``},
	{`chomp("a\r\n")`, `cty.StringVal("a")`, `cty.StringVal("a")`, ``},
	{`indent(2, "a\nb")`, `cty.StringVal("a\n  b")`, `cty.StringVal("a\n  b")`, ``},
	{`indent(-1, "a\nb")`, `panic in function implementation: strings: negative Repeat count`, `error: Call to function "indent" failed: function.invalid_argument: Indent: the number of spaces -1 is negative at .[0].`, `a negative count fails with a code at it (LS-022), where cty's panics, its message holding a goroutine's stack (Appendix B row 46)`},
	{`join(", ", ["a", "b"])`, `cty.StringVal("a, b")`, `cty.StringVal("a, b")`, ``},
	{`join(", ", ["a", null])`, `error: Invalid value for "lists" parameter: element 1 is null; cannot concatenate null values.`, `error: Call to function "join" failed: operation.null_operand: Join: element 1 is null, and has no text to give at .[1][1].`, `both fail; tenon's failure has a code, located at the element (LS-024)`},
	{`lower("ΟΔΟΣ")`, `cty.StringVal("οδοσ")`, `cty.StringVal("οδος")`, `Unicode's full case mapping: a capital sigma ending a word lowercases to the final sigma (LS-006, Appendix B row 42)`},
	{`upper("straße")`, `cty.StringVal("STRAßE")`, `cty.StringVal("STRASSE")`, `Unicode's full case mapping: ß is SS (LS-005, Appendix B row 42)`},
	{`title("foo.example.com")`, `cty.StringVal("Foo.Example.Com")`, `cty.StringVal("Foo.Example.Com")`, ``},
	{`replace("a-b-c", "-", "+")`, `cty.StringVal("a+b+c")`, `cty.StringVal("a+b+c")`, ``},
	{`replace("🇺🇸🇬🇧", "🇸🇬", "")`, `cty.StringVal("🇺🇧")`, `cty.StringVal("🇺🇸🇬🇧")`, `a match must begin and end where clusters do, and the Singapore flag is not in the US and British ones (LS-012, Appendix B row 45)`},
	{`split(",", "a,b,,c")`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal(""), cty.StringVal("c")})`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("b"), cty.StringVal(""), cty.StringVal("c")})`, ``},
	{`split("", "a\r\nb")`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("\r"), cty.StringVal("\n"), cty.StringVal("b")})`, `cty.ListVal([]cty.Value{cty.StringVal("a"), cty.StringVal("\r\n"), cty.StringVal("b")})`, `an empty separator splits clusters, and CR LF is one (LS-013, Appendix B row 45)`},
	{`strlen("🇺🇸👍🏽")`, `cty.NumberIntVal(2)`, `cty.NumberIntVal(2)`, ``},
	{`strrev("abc")`, `cty.StringVal("cba")`, `cty.StringVal("cba")`, ``},
	{`substr("hello", -3, 0)`, `cty.StringVal("llo")`, `cty.StringVal("")`, `a length of zero is the empty string, whatever the offset (LS-010, Appendix B row 43)`},
	{`substr("hello", 1, 3)`, `cty.StringVal("ell")`, `cty.StringVal("ell")`, ``},
	{`trim("  a  ", " ")`, `cty.StringVal("a")`, `cty.StringVal("a")`, ``},
	{`trimprefix("helloworld", "hello")`, `cty.StringVal("world")`, `cty.StringVal("world")`, ``},
	{`trimsuffix("helloworld", "world")`, `cty.StringVal("hello")`, `cty.StringVal("hello")`, ``},
	{`trimspace("  a \n")`, `cty.StringVal("a")`, `cty.StringVal("a")`, ``},
	{`format("%v", 1000000)`, `cty.StringVal("1e+06")`, `cty.StringVal("1000000")`, `%v of a number is its canonical text (LF-007, Appendix B row 47)`},
	{`format("%.2f", 2.675)`, `cty.StringVal("2.67")`, `cty.StringVal("2.68")`, `a tie rounds half to even on the exact decimal (LF-017, Appendix B row 49)`},
	{`format("%d", 1e999999)`, `cty.StringVal("999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999`, `error: Call to function "format" failed: function.too_large: Format: the answer passes 66176 bytes, 64 times the arguments' size and 64 KiB, the most it makes at .[0].`, `an answer past 64 times the arguments' size and 64 KiB fails before it is made (LF-022, Appendix B row 57)`},
	{`format("%s=%d", "a", 1)`, `cty.StringVal("a=1")`, `cty.StringVal("a=1")`, ``},
	{`format("%z", 1)`, `error: Call to function "format" failed: unsupported format verb 'z' in "%z" at offset 0.`, `error: Call to function "format" failed: format.invalid_syntax: Format: %z at byte 1 is no verb Format has at .[0].`, `both fail; tenon's failure has a code, located at the format (LF-001)`},
	{`formatlist("%s=%s", ["a", "b"], ["1", "2"])`, `cty.ListVal([]cty.Value{cty.StringVal("a=1"), cty.StringVal("b=2")})`, `cty.ListVal([]cty.Value{cty.StringVal("a=1"), cty.StringVal("b=2")})`, ``},
	{`formatlist("%z", [])`, `cty.ListValEmpty(cty.String)`, `error: Call to function "formatlist" failed: format.invalid_syntax: Format: %z at byte 1 is no verb Format has at .[0].`, `the format is checked though the list is empty (LF-018), where cty's accepts any format then`},
	{`regex("(\\w+)-(\\d+)", "web-42")`, `cty.TupleVal([]cty.Value{cty.StringVal("web"), cty.StringVal("42")})`, `cty.TupleVal([]cty.Value{cty.StringVal("web"), cty.StringVal("42")})`, ``},
	{`regex("(?P<x>a)(?P<x>b)", "ab")`, `cty.ObjectVal(map[string]cty.Value{"x":cty.StringVal("b")})`, `error: Call to function "regex" failed: regex.duplicate_group: Regex: the pattern names the group "x" twice, and one capture would be lost at .[0].`, `a pattern naming a group twice is refused (LR-005, Appendix B row 50), where cty keeps the later capture`},
	{`regexall("a*", "baaab")`, `cty.ListVal([]cty.Value{cty.StringVal(""), cty.StringVal("aaa"), cty.StringVal("")})`, `cty.ListVal([]cty.Value{cty.StringVal(""), cty.StringVal("aaa"), cty.StringVal("")})`, ``},
	{`regexreplace("abc", "(b)", "[$1x]")`, `cty.StringVal("a[]c")`, `error: Call to function "regexreplace" failed: regex.missing_group: RegexReplace: the replacement refers to a group named "1x", which the pattern does not have; ${1}x is group 1 followed by "x" at .[2].`, `a reference to a group the pattern does not have is refused (LR-012, Appendix B row 51), where cty writes nothing`},
	{`regexreplace("abc", "(b)", "[${1}x]")`, `cty.StringVal("a[1x]c")`, `cty.StringVal("a[1x]c")`, ``},
	{`jsonencode({a = [1, "x<y"], b = null})`, `cty.StringVal("{\"a\":[1,\"x\\u003cy\"],\"b\":null}")`, `cty.StringVal("{\"a\":[1,\"x\\u003cy\"],\"b\":null}")`, ``},
	{`jsonencode(1/3)`, `cty.StringVal("0.3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333`, `cty.StringVal("0.333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333")`, `tenon's quotient is 96 significant digits, exactly (NU-012), where cty's is 512 binary bits`},
	{`jsondecode("{\"a\": [1, null]}")`, `cty.ObjectVal(map[string]cty.Value{"a":cty.TupleVal([]cty.Value{cty.NumberIntVal(1), cty.NullVal(cty.DynamicPseudoType)})})`, `cty.ObjectVal(map[string]cty.Value{"a":cty.TupleVal([]cty.Value{cty.NumberIntVal(1), cty.NullVal(cty.DynamicPseudoType)})})`, ``},
	{`jsondecode("1]garbage")`, `cty.NumberIntVal(1)`, `error: Call to function "jsondecode" failed: json.invalid_syntax: the text is not JSON at byte 1: the end of the text was expected, and ']' was found at .[0].`, `text after the value fails (LE-004, Appendix B row 59), where cty reads past it after a closing bracket`},
	{`csvdecode("a,b\n1,2\n")`, `cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"a":cty.StringVal("1"), "b":cty.StringVal("2")})})`, `cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"a":cty.StringVal("1"), "b":cty.StringVal("2")})})`, ``},
	{`csvdecode("\ufeffa,b\n1,2\n")`, `cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"b":cty.StringVal("2"), "\ufeffa":cty.StringVal("1")})})`, `cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"a":cty.StringVal("1"), "b":cty.StringVal("2")})})`, `a leading byte order mark is passed over (LE-007, Appendix B row 61), where cty keeps it in the first name`},
	{`csvdecode(",a\n1,2\n")`, `cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"":cty.StringVal("1"), "a":cty.StringVal("2")})})`, `error: Call to function "csvdecode" failed: object.empty_name: CSVDecode: column 1 of the header has no name, and an attribute must have one at .[0].`, `an empty header name is refused (LE-008, Appendix B row 62), where cty makes an attribute of it`},
	{`formatdate("YYYY-MM-DD'T'hh:mm:ssZ", "2017-03-02T13:04:05-08:00")`, `cty.StringVal("2017-03-02T13:04:05-08:00")`, `cty.StringVal("2017-03-02T13:04:05-08:00")`, ``},
	{`formatdate("YYYY", "2017-03-02t13:04:05z")`, `error: Invalid value for "time" parameter: not a valid RFC3339 timestamp: missing required time introducer 'T'.`, `cty.StringVal("2017")`, `a small t and z are read, as RFC 3339 allows (LT-001, Appendix B row 64)`},
	{`formatdate("'abc''", "2017-03-02T13:04:05Z")`, `cty.StringVal("abc'")`, `error: Call to function "formatdate" failed: time.invalid_syntax: FormatDate: the quotation mark at byte 0 begins literal text that no quotation mark closes at .[0].`, `literal text no quotation mark closes is refused (LT-004, Appendix B row 66), where cty takes the doubled one as closing`},
	{`timeadd("2020-01-01T00:00:00Z", "1h30m")`, `cty.StringVal("2020-01-01T01:30:00Z")`, `cty.StringVal("2020-01-01T01:30:00Z")`, ``},
	{`timeadd("2020-01-01T00:00:00Z", "500ms")`, `cty.StringVal("2020-01-01T00:00:00Z")`, `cty.StringVal("2020-01-01T00:00:00.5Z")`, `the answer keeps the fraction of a second (LT-010, Appendix B row 68)`},
	{`timeadd("9999-12-31T23:00:00Z", "1h")`, `cty.StringVal("10000-01-01T00:00:00Z")`, `error: Call to function "timeadd" failed: time.out_of_range: TimeAdd: "1h" moves "9999-12-31T23:00:00Z" outside the years 0000 to 9999, which no timestamp holds at .[1].`, `an answer outside the years 0000 to 9999 fails (LT-010, Appendix B row 70), where cty writes one its own timestamps refuse`},
	{`upper(maybenull)`, `cty.UnknownVal(cty.String).RefineNotNull()`, `cty.UnknownVal(cty.String).RefineNotNull()`, ``},
	{`format("x=%s", maybenull)`, `cty.UnknownVal(cty.String).Refine().NotNull().StringPrefixFull("x").NewValue()`, `cty.UnknownVal(cty.String).Refine().NotNull().StringPrefixFull("x").NewValue()`, ``},
	{`length(unknown == 1 ? ["a"] : ["b", "c"])`, `cty.UnknownVal(cty.Number).Refine().NotNull().NumberLowerBound(cty.NumberIntVal(0), true).NumberUpperBound(cty.NumberInt`, `cty.UnknownVal(cty.Number).Refine().NotNull().NumberLowerBound(cty.NumberIntVal(0), true).NewValue()`, `a length not known yet has no greatest value but the lengths' own, where cty's refinement says the largest int64, its lengths' type`},
}
