package uni

// Extended grapheme clusters, as UAX #29 sets them out. The data they are
// found by is generated by tools/unigen from Unicode's own files and held in
// this package, as the normalization data is, so the Unicode version tenon
// states follows neither the Go toolchain a consumer builds with nor any
// module their build requires.

// A graphemeBreak is a code point's Grapheme_Cluster_Break value, by UAX #29's
// names, with the Extended_Pictographic code points, all of them Other, told
// apart from the rest of Other.
type graphemeBreak uint8

const (
	gbOther graphemeBreak = iota
	gbCR
	gbLF
	gbControl
	gbExtend
	gbZWJ
	gbRegionalIndicator
	gbPrepend
	gbSpacingMark
	gbL
	gbV
	gbT
	gbLV
	gbLVT
	gbExtendedPictographic
)

// graphemeRange gives the code points from first to last one value.
type graphemeRange struct {
	first, last rune
	value       graphemeBreak
}

// GraphemeCount returns the number of extended grapheme clusters in s, as
// Unicode Standard Annex #29 defines them for UnicodeVersion. That count is the
// length of a string value; the number of scalar values and the number of
// bytes, len(s), are different measures.
func GraphemeCount(s string) int {
	n := 0
	var g segmenter
	for _, r := range s {
		if g.begins(graphemeBreakOf(r)) {
			n++
		}
	}
	return n
}

// segmenter reads text a code point at a time and finds where its clusters
// begin. Each rule of UAX #29 decides whether a cluster begins at a code point
// from that code point and the text before it, so what follows never moves a
// boundary already found, and what the segmenter keeps of the text is what the
// rules look back at: the last code point's value, and the runs that GB11,
// GB12 and GB13 look along.
type segmenter struct {
	started bool
	last    graphemeBreak
	// pictographic says the text ends in an Extended_Pictographic code point
	// and any Extend after it, and joined that a ZWJ follows those (GB11).
	pictographic, joined bool
	// oddRegional says the text ends in an odd number of regional indicators
	// (GB12, GB13).
	oddRegional bool
}

// begins reads a code point whose value is v and reports whether a cluster
// begins with it.
func (g *segmenter) begins(v graphemeBreak) bool {
	begins := g.breaksBefore(v)
	g.started, g.last = true, v
	g.joined = v == gbZWJ && g.pictographic
	g.pictographic = v == gbExtendedPictographic || v == gbExtend && g.pictographic
	g.oddRegional = v == gbRegionalIndicator && !g.oddRegional
	return begins
}

// breaksBefore applies UAX #29's rules, in their order, to the text read so
// far and a code point whose value is v after it.
func (g *segmenter) breaksBefore(v graphemeBreak) bool {
	last := g.last
	switch {
	case !g.started:
		return true // GB1
	case last == gbCR && v == gbLF:
		return false // GB3
	case last == gbControl || last == gbCR || last == gbLF:
		return true // GB4
	case v == gbControl || v == gbCR || v == gbLF:
		return true // GB5
	case last == gbL && (v == gbL || v == gbV || v == gbLV || v == gbLVT):
		return false // GB6
	case (last == gbLV || last == gbV) && (v == gbV || v == gbT):
		return false // GB7
	case (last == gbLVT || last == gbT) && v == gbT:
		return false // GB8
	case v == gbExtend || v == gbZWJ:
		return false // GB9
	case v == gbSpacingMark:
		return false // GB9a
	case last == gbPrepend:
		return false // GB9b
	case g.joined && v == gbExtendedPictographic:
		return false // GB11
	case g.oddRegional && v == gbRegionalIndicator:
		return false // GB12, GB13
	}
	return true // GB999
}

// graphemeBreakOf returns the value of r. ASCII is read without the table, as
// unigen checks the data allows: it is Other but for the controls, CR and LF
// among them.
func graphemeBreakOf(r rune) graphemeBreak {
	if r >= 0x80 {
		return tabulatedBreak(r)
	}
	switch {
	case r >= 0x20 && r != 0x7F:
		return gbOther
	case r == '\r':
		return gbCR
	case r == '\n':
		return gbLF
	}
	return gbControl
}

// tabulatedBreak returns the value of r, which is not ASCII. A Hangul syllable
// is read without the table too, as unigen checks the data allows: LV where it
// has no trailing consonant, and LVT where it has one.
func tabulatedBreak(r rune) graphemeBreak {
	if i := r - hangulSBase; i >= 0 && i < hangulSCount {
		if i%hangulTCount == 0 {
			return gbLV
		}
		return gbLVT
	}
	lo, hi := 0, len(graphemeBreaks)
	for lo < hi {
		m := int(uint(lo+hi) >> 1)
		switch e := &graphemeBreaks[m]; {
		case r < e.first:
			hi = m
		case r > e.last:
			lo = m + 1
		default:
			return e.value
		}
	}
	return gbOther
}
