package uni

import (
	"testing"
	"unicode/utf8"

	"github.com/kmoneil/tenon/internal/conformance"
)

// TestConformance_ST003_UnicodeVersion pins the Unicode data this package
// holds to UnicodeVersion. Regenerating the normalization or the segmentation
// tables from another version moves them, which changes which strings are
// equal or how long they are. That must be a deliberate change of
// UnicodeVersion, never a silent one.
//
// Neither follows the toolchain a consumer builds with, or a module their
// build requires: both are this package's own, generated by tools/unigen and
// committed, and tenon requires no other module. tools/unigen's tests hold
// them to Unicode's own conformance tests for the version, on every
// toolchain.
func TestConformance_ST003_UnicodeVersion(t *testing.T) {
	conformance.Covers(t, "ST-003")
	if tablesVersion != UnicodeVersion {
		t.Errorf("the normalization data is Unicode %s, but UnicodeVersion is %s", tablesVersion, UnicodeVersion)
	}
	if graphemeTablesVersion != UnicodeVersion {
		t.Errorf("the segmentation data is Unicode %s, but UnicodeVersion is %s", graphemeTablesVersion, UnicodeVersion)
	}
	// A rule that Unicode 15.1 added pins what segmentation does with its data:
	// from 15.1 on (GB9c), a virama joins Devanagari consonants into one
	// cluster, while in 15.0 the conjunct KSSA is two clusters.
	if got := GraphemeCount("\u0915\u094d\u0937"); got != 2 {
		t.Errorf("KSSA segments into %d clusters, not the 2 of Unicode 15.0; the segmentation data has moved from UnicodeVersion %s", got, UnicodeVersion)
	}
}

func TestConformance_ST005_Length(t *testing.T) {
	conformance.Covers(t, "ST-005")
	for _, tt := range []struct {
		name                      string
		s                         string
		graphemes, scalars, bytes int
	}{
		{"empty", "", 0, 0, 0},
		{"ASCII", "hello", 5, 5, 5},
		{"CRLF is one cluster", "a\r\nb", 3, 4, 4},
		{"combining marks", "x\u0301\u0302", 1, 3, 5},
		{"precomposed letter", "caf\u00e9", 4, 4, 5},
		{"Hangul syllables", "\ud55c\uae00", 2, 2, 6},
		{"emoji with a skin tone", "\U0001f44d\U0001f3fd", 1, 2, 8},
		{"ZWJ sequence", "\U0001f468\u200d\U0001f469\u200d\U0001f467", 1, 5, 18},
		{"flag", "\U0001f1ef\U0001f1f5", 1, 2, 8},
		{"odd number of regional indicators", "\U0001f1ef\U0001f1f5\U0001f1fa", 2, 3, 12},
		{"two flags", "\U0001f1ef\U0001f1f5\U0001f1fa\U0001f1f8", 2, 4, 16},
		{"a control breaks before a mark", "a\t\U00000301", 3, 3, 4},
		{"a leading jamo joins a syllable", "\U00001100\U00001100\U00001161", 1, 2, 6},
		{"a syllable without a trailing consonant takes a vowel", "\U0000AC00\U00001161", 1, 2, 6},
		{"a syllable with a trailing consonant takes another", "\U0000AC01\U000011A8", 1, 2, 6},
		{"a spacing mark", "\U00000915\U0000093F", 1, 2, 6},
		{"a prepended mark", "\U00000600\U00000661", 1, 2, 4},
		{"ZWJ joins pictographs only", "a\U0000200D\U0001F469", 2, 3, 8},
		// One string on which the three measures all differ.
		{"combining mark and flag", "x\u0301\U0001f1ef\U0001f1f5", 2, 4, 11},
	} {
		s, err := Canonical(tt.s)
		if err != nil {
			t.Fatalf("%s: %v", tt.name, err)
		}
		if g, n, b := GraphemeCount(s), scalarCount(s), len(s); g != tt.graphemes || n != tt.scalars || b != tt.bytes {
			t.Errorf("%s: %d graphemes, %d scalar values, %d bytes; want %d, %d, %d", tt.name, g, n, b, tt.graphemes, tt.scalars, tt.bytes)
		}
	}
}

// scalarCount returns the number of Unicode scalar values in s, which must be
// well-formed UTF-8: the measure the table's scalars column pins, beside the
// grapheme and byte counts.
func scalarCount(s string) int {
	return utf8.RuneCountInString(s)
}
