package uni

import (
	"cmp"
	"slices"
	"unicode/utf8"
)

// Normalization Form C, as UAX #15 sets it out: decompose canonically, put the
// result into canonical order, then compose canonically. The data it runs on
// is generated by tools/unigen and held in this package, so the Unicode
// version tenon states does not follow whichever Go toolchain a consumer
// builds with.
//
// This is plain NFC. It does not apply the Stream-Safe Text Process, which
// inserts U+034F into a run of more than thirty non-starters: [ST-002] makes
// two strings equal exactly when their normalized forms are identical, and a
// string that gained a code point on the way in is not the string that was
// given. Nothing else that normalizes by UAX #15 would insert it either.

// The Hangul syllables compose and decompose by arithmetic rather than from a
// table, which is why unigen leaves them out of one. The names are UAX #15's.
const (
	hangulSBase  = 0xAC00
	hangulLBase  = 0x1100
	hangulVBase  = 0x1161
	hangulTBase  = 0x11A7
	hangulLCount = 19
	hangulVCount = 21
	hangulTCount = 28
	hangulNCount = hangulVCount * hangulTCount
	hangulSCount = hangulLCount * hangulNCount
)

// nfc returns s in Normalization Form C.
func nfc(s string) string {
	if isNormalized(s) {
		return s
	}
	if !utf8.ValidString(s) {
		// Text that is not well-formed, which every caller is to have refused
		// already. Decomposing would write the replacement character over the
		// bytes; returning them is the one answer that loses nothing. The
		// check is here rather than in isNormalized, which stops at the first
		// code point it cannot vouch for and so may never reach the bytes.
		return s
	}
	rs := decompose(make([]rune, 0, len(s)), s)
	reorder(rs)
	return string(compose(rs))
}

// isNormalized reports whether s is already in Normalization Form C, by the
// quick check of UAX #15: a string is, where every code point is one that the
// form leaves alone and cannot compose onto what comes before it, and the
// combining classes within each run of non-starters do not fall.
//
// It answers false wherever it cannot tell, so a false costs a normalization
// that may turn out to change nothing, and never a wrong answer.
func isNormalized(s string) bool {
	last := uint8(0)
	for _, r := range s {
		if r < 0x80 {
			// No ASCII code point has a canonical decomposition or a combining
			// class, and no two of them compose, which unigen checks.
			last = 0
			continue
		}
		cc := combiningClass(r)
		if cc != 0 && cc < last {
			return false
		}
		if _, no := slices.BinarySearch(rewritten[:], r); no {
			return false
		}
		if _, maybe := slices.BinarySearch(composing[:], r); maybe {
			return false
		}
		last = cc
	}
	return true
}

// combiningClass returns the canonical combining class of r. A starter has
// class zero, and all but 922 code points are starters.
func combiningClass(r rune) uint8 {
	i, ok := slices.BinarySearchFunc(combiningClasses[:], r, func(e uint32, r rune) int {
		return cmp.Compare(rune(e>>8), r)
	})
	if !ok {
		return 0
	}
	return uint8(combiningClasses[i])
}

// decompose appends the full canonical decomposition of s to dst. Each
// tabulated decomposition is already full, so none has to be applied twice.
func decompose(dst []rune, s string) []rune {
	for _, r := range s {
		if i := r - hangulSBase; i >= 0 && i < hangulSCount {
			dst = append(dst, hangulLBase+i/hangulNCount, hangulVBase+(i%hangulNCount)/hangulTCount)
			if t := i % hangulTCount; t != 0 {
				dst = append(dst, hangulTBase+t)
			}
			continue
		}
		j, ok := slices.BinarySearch(decomposable[:], r)
		if !ok {
			dst = append(dst, r)
			continue
		}
		for _, d := range decompositions[decompositionOffsets[j]:decompositionOffsets[j+1]] {
			dst = append(dst, d)
		}
	}
	return dst
}

// reorder puts rs into canonical order in place: within each run of
// non-starters the combining classes do not fall, and runes of one class keep
// the order they arrived in. The runs are short, so this is an insertion sort.
func reorder(rs []rune) {
	for i := 1; i < len(rs); i++ {
		cc := combiningClass(rs[i])
		if cc == 0 {
			continue
		}
		for j := i; j > 0; j-- {
			if prev := combiningClass(rs[j-1]); prev == 0 || prev <= cc {
				break
			}
			rs[j-1], rs[j] = rs[j], rs[j-1]
		}
	}
}

// compose applies the canonical composition algorithm in place and returns the
// composed prefix of rs. Every rune it writes is at an index it has already
// read, so writing into rs as it goes is safe.
func compose(rs []rune) []rune {
	out := rs[:0]
	starter := -1
	for _, r := range rs {
		cc := combiningClass(r)
		if starter >= 0 {
			// A rune is blocked from the starter where something between them
			// has a class at least its own. What lies between is in canonical
			// order and holds no starter, so the rune written last is the one
			// with the greatest class.
			blocked := len(out) > starter+1 && combiningClass(out[len(out)-1]) >= cc
			if !blocked {
				if p, ok := primaryComposite(out[starter], r); ok {
					out[starter] = p
					continue
				}
			}
		}
		if cc == 0 {
			starter = len(out)
		}
		out = append(out, r)
	}
	return out
}

// primaryComposite returns the code point that a and b compose to, and whether
// they compose. The composition exclusions are not in the table, so they do
// not come back from it.
func primaryComposite(a, b rune) (rune, bool) {
	// A Hangul leading consonant and a vowel make a syllable, and a syllable
	// without a trailing consonant takes one.
	if l := a - hangulLBase; l >= 0 && l < hangulLCount {
		if v := b - hangulVBase; v >= 0 && v < hangulVCount {
			return hangulSBase + l*hangulNCount + v*hangulTCount, true
		}
	}
	if s := a - hangulSBase; s >= 0 && s < hangulSCount && s%hangulTCount == 0 {
		if t := b - hangulTBase; t > 0 && t < hangulTCount {
			return a + t, true
		}
	}
	i, ok := slices.BinarySearch(compositionKeys[:], uint64(a)<<21|uint64(b))
	if !ok {
		return 0, false
	}
	return compositionValues[i], true
}
