package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"slices"
	"strings"
)

// recordedCode is one entry of the committed record of diagnostic codes. A
// code, once recorded, stays for good: it leaves the registry only by being
// marked withdrawn here, and a withdrawn code never returns.
type recordedCode struct {
	Code      string `json:"code"`
	Withdrawn bool   `json:"withdrawn,omitempty"`
}

// codeRecordFile is the layout of conformance/codes.json.
type codeRecordFile struct {
	Format int            `json:"format"`
	About  string         `json:"about"`
	Codes  []recordedCode `json:"codes"`
}

const codeRecordAbout = "The diagnostic codes ever declared in codes.go. Generated by `make codes`; " +
	"do not edit except to mark a code withdrawn when it leaves the registry."

// readCodeRecord reads the committed record of codes.
func readCodeRecord(path string) ([]recordedCode, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	var f codeRecordFile
	if err := dec.Decode(&f); err != nil || f.Format != 1 {
		return nil, fmt.Errorf("%s: not a code record", display(path))
	}
	return f.Codes, nil
}

// writeCodeRecord writes the record, sorted by code.
func writeCodeRecord(path string, codes []recordedCode) error {
	slices.SortFunc(codes, func(a, b recordedCode) int { return strings.Compare(a.Code, b.Code) })
	data, err := json.MarshalIndent(codeRecordFile{Format: 1, About: codeRecordAbout, Codes: codes}, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// checkCodeRecord holds the registry to the record: a recorded code that is
// not withdrawn must still be declared, a withdrawn one must not return, and
// a declared code must be recorded.
func checkCodeRecord(w io.Writer, registry []string, record []recordedCode, recordPath string) error {
	declared := make(map[string]bool, len(registry))
	for _, c := range registry {
		declared[c] = true
	}
	var msgs []string
	withdrawn := 0
	recorded := make(map[string]bool, len(record))
	for _, r := range record {
		recorded[r.Code] = true
		switch {
		case r.Withdrawn && declared[r.Code]:
			msgs = append(msgs, fmt.Sprintf("code %s was withdrawn and cannot be reinstated; mint a new code instead", r.Code))
		case !r.Withdrawn && !declared[r.Code]:
			msgs = append(msgs, fmt.Sprintf("code %s has disappeared from the registry; mark it withdrawn in %s instead", r.Code, display(recordPath)))
		}
		if r.Withdrawn {
			withdrawn++
		}
	}
	for _, c := range registry {
		if !recorded[c] {
			msgs = append(msgs, fmt.Sprintf("code %s is not recorded in %s; record it with `make codes`", c, display(recordPath)))
		}
	}
	if len(msgs) > 0 {
		return errors.New("diagnostic codes are permanent:\n  " + strings.Join(msgs, "\n  "))
	}
	fmt.Fprintf(w, "rulecheck: code record up to date (%d codes, %d withdrawn)\n", len(record)-withdrawn, withdrawn)
	return nil
}

// updateCodeRecord returns the record with every declared code recorded. A
// recorded code that is neither withdrawn nor declared is refused, since
// recording its absence is what marking it withdrawn is for.
func updateCodeRecord(registry []string, record []recordedCode) ([]recordedCode, error) {
	declared := make(map[string]bool, len(registry))
	for _, c := range registry {
		declared[c] = true
	}
	recorded := make(map[string]bool, len(record))
	out := slices.Clone(record)
	for _, r := range record {
		recorded[r.Code] = true
		switch {
		case r.Withdrawn && declared[r.Code]:
			return nil, fmt.Errorf("code %s was withdrawn and cannot be reinstated; mint a new code instead", r.Code)
		case !r.Withdrawn && !declared[r.Code]:
			return nil, fmt.Errorf("code %s has disappeared from the registry; mark it withdrawn instead", r.Code)
		}
	}
	for _, c := range registry {
		if !recorded[c] {
			out = append(out, recordedCode{Code: c})
		}
	}
	return out, nil
}
