package main

import (
	"bytes"
	"fmt"
	"go/format"
	"maps"
	"slices"
	"strings"
	"unicode"
)

// renderTables returns the source of internal/uni's tables.go: the
// normalization data and the general categories.
func renderTables(n normalization, categories [][2]rune) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/unigen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package uni\n\n")
	fmt.Fprintf(&b, "// The data of Unicode %s: canonical combining classes, canonical\n"+
		"// decompositions and primary composites. The Hangul syllables are left out,\n"+
		"// composing and decomposing by arithmetic instead.\n\n", version)
	fmt.Fprintf(&b, "// tablesVersion is the Unicode version this data was generated from. A test\n"+
		"// holds it to UnicodeVersion, so the two cannot drift apart unremarked.\n"+
		"const tablesVersion = %q\n\n", version)

	// Combining classes, packed as the code point in the high bits and the
	// class in the low eight, sorted so that a lookup is a binary search.
	fmt.Fprintf(&b, "// combiningClasses holds every code point of nonzero canonical combining\n"+
		"// class, packed as the code point shifted up by eight with the class beneath,\n"+
		"// in code point order.\nvar combiningClasses = [...]uint32{\n")
	for _, r := range slices.Sorted(maps.Keys(n.ccc)) {
		fmt.Fprintf(&b, "0x%X<<8 | 0x%02X,\n", r, n.ccc[r])
	}
	fmt.Fprintf(&b, "}\n\n")

	// Decompositions: the code points in order, the offset of each one's
	// decomposition in a single string, and that string.
	fmt.Fprintf(&b, "// decomposable holds every code point with a canonical decomposition, in\n"+
		"// order. The decomposition of decomposable[i] is decompositions sliced from\n"+
		"// decompositionOffsets[i] to decompositionOffsets[i+1]. Each is the full\n"+
		"// canonical decomposition, so it never has to be applied again.\n"+
		"var decomposable = [...]rune{\n")
	for _, r := range n.decomposable {
		fmt.Fprintf(&b, "0x%X,\n", r)
	}
	fmt.Fprintf(&b, "}\n\n")
	var text strings.Builder
	offsets := make([]int, 0, len(n.decomposable)+1)
	for _, r := range n.decomposable {
		offsets = append(offsets, text.Len())
		text.WriteString(n.decomp[r])
	}
	offsets = append(offsets, text.Len())
	fmt.Fprintf(&b, "var decompositionOffsets = [...]uint32{\n")
	for _, o := range offsets {
		fmt.Fprintf(&b, "%d,\n", o)
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "const decompositions = %s\n\n", quoteEscaped(text.String()))

	// Primary composites, packed as the two code points in one key, sorted so
	// that a lookup is a binary search.
	keys := slices.SortedFunc(maps.Keys(n.composed), func(x, y pair) int {
		if x.a != y.a {
			return int(x.a) - int(y.a)
		}
		return int(x.b) - int(y.b)
	})
	fmt.Fprintf(&b, "// compositionKeys holds the pairs that form a primary composite, packed as\n"+
		"// the first code point shifted up by 21 with the second beneath, in order.\n"+
		"// compositionValues[i] is what compositionKeys[i] composes to.\n"+
		"var compositionKeys = [...]uint64{\n")
	for _, p := range keys {
		fmt.Fprintf(&b, "0x%X<<21 | 0x%X,\n", p.a, p.b)
	}
	fmt.Fprintf(&b, "}\n\nvar compositionValues = [...]rune{\n")
	for _, p := range keys {
		fmt.Fprintf(&b, "0x%X,\n", n.composed[p])
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// rewritten holds the code points that Normalization Form C does not leave\n"+
		"// as they are on their own: the singleton decompositions and the composition\n"+
		"// exclusions. In order.\nvar rewritten = [...]rune{\n")
	for _, r := range n.rewritten {
		fmt.Fprintf(&b, "0x%X,\n", r)
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "// composing holds the code points that end a primary composite, the Hangul\n"+
		"// vowels and trailing consonants among them, so that a string holding one has\n"+
		"// to be normalized to find out what it does. In order.\nvar composing = [...]rune{\n")
	for _, r := range slices.Sorted(maps.Keys(n.composing)) {
		fmt.Fprintf(&b, "0x%X,\n", r)
	}
	fmt.Fprintf(&b, "}\n\n")

	// The general categories the display form asks about, as the ranges of
	// what it does not escape.
	fmt.Fprintf(&b, "// assigned holds the ranges of code points whose general category is a\n"+
		"// letter, mark, number, punctuation or symbol: everything that is not a\n"+
		"// separator or an other. Each range is a first and a last code point, and the\n"+
		"// ranges are in order and do not touch.\nvar assigned = [...][2]rune{\n")
	for _, c := range categories {
		fmt.Fprintf(&b, "{0x%X, 0x%X},\n", c[0], c[1])
	}
	fmt.Fprintf(&b, "}\n")
	return formatted(b.Bytes())
}

// renderGraphemes returns the source of internal/uni's grapheme_tables.go:
// the segmentation data, as the ranges of code points that share a value
// other than Other, but for the Hangul syllables, whose values the segmenter
// works out as the normalizer decomposes them.
func renderGraphemes(s segmentation) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by tools/unigen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package uni\n\n")
	fmt.Fprintf(&b, "// The data of Unicode %s that extended grapheme clusters are found by: the\n"+
		"// Grapheme_Cluster_Break values of its GraphemeBreakProperty.txt, and the\n"+
		"// Extended_Pictographic code points of its emoji-data.txt. The Hangul\n"+
		"// syllables are left out, their values following from their decompositions.\n\n", version)
	fmt.Fprintf(&b, "// graphemeTablesVersion is the Unicode version this data was generated from.\n"+
		"// A test holds it to UnicodeVersion, so the two cannot drift apart unremarked.\n"+
		"const graphemeTablesVersion = %q\n\n", version)
	fmt.Fprintf(&b, "// graphemeBreaks holds every code point whose value is not Other, or which\n"+
		"// is Extended_Pictographic, but for the Hangul syllables, as ranges that share\n"+
		"// a value. The ranges are in order and do not overlap.\n"+
		"var graphemeBreaks = [...]graphemeRange{\n")
	for _, g := range s.ranges() {
		fmt.Fprintf(&b, "{0x%04X, 0x%04X, %s},\n", g.first, g.last, g.value)
	}
	fmt.Fprintf(&b, "}\n")
	return formatted(b.Bytes())
}

// valueRange is code points from first to last that share a value.
type valueRange struct {
	first, last rune
	value       string
}

// ranges returns the code points that s gives a value, but for the Hangul
// syllables, as the fewest ranges that share one, in order.
func (s segmentation) ranges() []valueRange {
	var out []valueRange
	for r := rune(0); r <= unicode.MaxRune; r++ {
		v := s[r]
		if v == "" || r >= hangulFirst && r <= hangulLastSyllable {
			continue
		}
		if n := len(out); n > 0 && out[n-1].last == r-1 && out[n-1].value == v {
			out[n-1].last = r
			continue
		}
		out = append(out, valueRange{r, r, v})
	}
	return out
}

// formatted returns src as gofmt formats it.
func formatted(src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("the generated source does not parse: %w", err)
	}
	return out, nil
}

// quoteEscaped renders s as a Go string literal in which every rune is written
// by its code point, so that the generated file holds no text of its own and
// is legible in any editor.
func quoteEscaped(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		fmt.Fprintf(&b, "\\U%08X", r)
	}
	b.WriteByte('"')
	return b.String()
}
